// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BikeStoresapp1.Models
{
    public partial class brands
    {
        public brands()
        {
            products = new HashSet<products>();
        }

        public int brand_id { get; set; }
        public string brand_name { get; set; }

        public virtual ICollection<products> products { get; set; }
    }
}