// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BikeStoresapp1.Models
{
    public partial class products
    {
        public products()
        {
            order_items = new HashSet<order_items>();
            stocks = new HashSet<stocks>();
        }

        public int product_id { get; set; }
        public string product_name { get; set; }
        public int brand_id { get; set; }
        public int category_id { get; set; }
        public short model_year { get; set; }
        public decimal list_price { get; set; }

        public virtual brands brand { get; set; }
        public virtual categories category { get; set; }
        public virtual ICollection<order_items> order_items { get; set; }
        public virtual ICollection<stocks> stocks { get; set; }
    }
}