// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models
{
    public partial class Country
    {
        public Country()
        {
            Campus = new HashSet<Campus>();
            Faculty = new HashSet<Faculty>();
            State = new HashSet<State>();
            Student = new HashSet<Student>();
            University = new HashSet<University>();
        }

        public int CountryId { get; set; }
        public string CountryName { get; set; }

        public virtual ICollection<Campus> Campus { get; set; }
        public virtual ICollection<Faculty> Faculty { get; set; }
        public virtual ICollection<State> State { get; set; }
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<University> University { get; set; }
    }
}