// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models
{
    public partial class Designation
    {
        public Designation()
        {
            Faculty = new HashSet<Faculty>();
        }

        public int DesignationId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Faculty> Faculty { get; set; }
    }
}