// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models
{
    public partial class Room
    {
        public Room()
        {
            SemesterCourse = new HashSet<SemesterCourse>();
        }

        public int RoomId { get; set; }
        public int BuildingId { get; set; }
        public string RoomName { get; set; }
        public bool IsLibrary { get; set; }
        public bool IsComputerLab { get; set; }
        public bool IsOtherLab { get; set; }
        public int Capacity { get; set; }

        public virtual Building Building { get; set; }
        public virtual ICollection<SemesterCourse> SemesterCourse { get; set; }
    }
}