// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models
{
    public partial class State
    {
        public State()
        {
            Campus = new HashSet<Campus>();
            City = new HashSet<City>();
            Faculty = new HashSet<Faculty>();
            Student = new HashSet<Student>();
            University = new HashSet<University>();
        }

        public int StateId { get; set; }
        public int CountryId { get; set; }
        public string StateName { get; set; }

        public virtual Country Country { get; set; }
        public virtual ICollection<Campus> Campus { get; set; }
        public virtual ICollection<City> City { get; set; }
        public virtual ICollection<Faculty> Faculty { get; set; }
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<University> University { get; set; }
    }
}