// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Testapp.Models
{
    public partial class ProductionBrands
    {
        public int BrandId { get; set; }
        public string BrandName { get; set; }

        public virtual ProductionProducts ProductionProducts { get; set; }
    }
}