// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Smallapp.Models;

namespace Smallapp.Data
{
    public partial class SmallappContext : DbContext
    {
        public SmallappContext()
        {
        }

        public SmallappContext(DbContextOptions<SmallappContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AGENTS> AGENTS { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {

                optionsBuilder.UseSqlServer("Data Source=KEVINPC\\SQLEXPRESS;Initial Catalog=Small;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AGENTS>(entity =>
            {
                entity.HasKey(e => e.AGENT_CODE)
                    .HasName("PK__AGENTS__843A8BBA84DAAE43");

                entity.Property(e => e.AGENT_CODE)
                    .HasMaxLength(6)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.AGENT_NAME)
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.PHONE_NO)
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.WORKING_AREA)
                    .HasMaxLength(35)
                    .IsUnicode(false)
                    .IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}